version: '3.8'

services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng-we-media
    restart: unless-stopped
    ports:
      - "18080:8080"
    environment:
      - HTTP_PROXY=http://192.168.5.112:6478
      - HTTPS_PROXY=http://192.168.5.112:6478
      - http_proxy=http://192.168.5.112:6478
      - https_proxy=http://192.168.5.112:6478